<a href="https://colab.research.google.com/github/MuhammadDAFFA28/MuhammadDaffa-Tugas-DAA-P2/blob/main/Latihan_pertemuan_3_Muhammad_Daffa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
aList = ["John", 33, "Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [6]:
import datetime as dt
tanggal = dt.date.today()
mahasiswa = ["Muhammad Daffa","2023071036","Prodi Informatika","DAA",tanggal,"universitas pembangunan jaya"]
print(mahasiswa)

['Muhammad Daffa', '2023071036', 'Prodi Informatika', 'DAA', datetime.date(2024, 9, 19), 'universitas pembangunan jaya']


In [8]:
print ("Niim", mahasiswa[1])
print ("Kampus", mahasiswa[5])

Niim 2023071036
Kampus universitas pembangunan jaya


In [23]:
for aMahasiswa in mahasiswa:
  print (aMahasiswa, 'UPJ')

Muhammad Daffa UPJ
2023071036 UPJ
Prodi Informatika UPJ
DAA UPJ
2024-09-19 UPJ
universitas pembangunan jaya UPJ


In [21]:
bin_colors=["Red", "Green", "Blue", "Yellow"]
bin_colors[1:3]

['Green', 'Blue']

In [22]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
for aColor in bin_colors:
 print(aColor + 'square')

Redsquare
Greensquare
Bluesquare
Yellowsquare


In [25]:
tup_colors = ('Red', 'Green', 'Blue', 'Yellow')
tup_colors[0:]

('Red', 'Green', 'Blue', 'Yellow')

In [26]:
tup_colors = ('Prodi Informatika', '2023071036', 'UPJ')
tup_colors[0:]

('Prodi Informatika', '2023071036', 'UPJ')

In [27]:
NESTED_TUPLE = (100,(200,400,600),300,(400,800))
NESTED_TUPLE

(100, (200, 400, 600), 300, (400, 800))

In [31]:
bin_colors ={
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}
bin_colors.get('manual_color')

'Yellow'

In [48]:
yellow_set = {'dandelions', 'leaves', 'fire hydrant'}
red_set = {'blood', 'rose', 'fire hydrant', 'leaves'}

yellow_and_red = yellow_set.intersection(red_set)

yellow_only = yellow_set - yellow_and_red
red_only = red_set - yellow_and_red

yellow_or_red = yellow_only.union(red_only, yellow_and_red)

print("yellow/red:", yellow_or_red)
print("yellow&red:", yellow_and_red)


yellow/red: {'fire hydrant', 'dandelions', 'rose', 'leaves', 'blood'}
yellow&red: {'fire hydrant', 'leaves'}


In [50]:
import pandas as pd
from IPython.display import display

df = pd.DataFrame([
    ['1', 'Informatika', 32, 30, 20],
    ['2', 'Sistem Informasi', 23, 30, 25],
    ['3', 'Teknik sipil', 40, 30, 10]
], columns=['No', 'Prodi', 'Mahasiswa', 'Laki-laki', 'Perempuan'])

print(df)
display(df)

  No             Prodi  Mahasiswa  Laki-laki  Perempuan
0  1       Informatika         32         30         20
1  2  Sistem Informasi         23         30         25
2  3      Teknik sipil         40         30         10


No             Prodi  Mahasiswa  Laki-laki  Perempuan
0  1       Informatika         32         30         20
1  2  Sistem Informasi         23         30         25
2  3      Teknik sipil         40         30         10

In [49]:
import numpy as np
myMatrix = np.array([[100,200,300],[700,600,500],[900,1000,800]])
print(myMatrix)

transpose_matrix = myMatrix.transpose()
print(transpose_matrix)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [ ]:
import pandas as pd
